/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  boolean,
  numeric,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_bookings_status = pgEnum("enum_bookings_status", [
  "pending",
  "confirmed",
  "cancelled",
]);

export const admins_sessions = pgTable(
  "admins_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("admins_sessions_order_idx").on(columns._order),
    index("admins_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [admins.id],
      name: "admins_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const admins = pgTable(
  "admins",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    is_admin: boolean("is_admin").notNull().default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("admins_updated_at_idx").on(columns.updatedAt),
    index("admins_created_at_idx").on(columns.createdAt),
    uniqueIndex("admins_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const services = pgTable("services", {
  id: varchar("id").primaryKey(),
  name: varchar("name").notNull(),
  description: varchar("description").notNull(),
  duration_minutes: numeric("duration_minutes", { mode: "number" }).notNull(),
  price: numeric("price", { mode: "number" }).notNull(),
  is_active: boolean("is_active").notNull().default(true),
  sort_order: numeric("sort_order", { mode: "number" }).notNull().default(0),
  created_at: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  updated_at: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const time_slots = pgTable("time_slots", {
  id: varchar("id").primaryKey(),
  date: varchar("date").notNull(),
  starts_at: varchar("starts_at").notNull(),
  ends_at: varchar("ends_at").notNull(),
  is_available: boolean("is_available").notNull().default(true),
  created_at: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  updated_at: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const testimonials = pgTable("testimonials", {
  id: varchar("id").primaryKey(),
  author_name: varchar("author_name").notNull(),
  body: varchar("body").notNull(),
  rating: numeric("rating", { mode: "number" }).notNull(),
  is_visible: boolean("is_visible").notNull().default(true),
  sort_order: numeric("sort_order", { mode: "number" }).notNull().default(0),
  created_at: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  updated_at: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const bookings = pgTable(
  "bookings",
  {
    id: varchar("id").primaryKey(),
    service_id: varchar("service_id_id")
      .notNull()
      .references(() => services.id, {
        onDelete: "set null",
      }),
    time_slot_id: varchar("time_slot_id_id")
      .notNull()
      .references(() => time_slots.id, {
        onDelete: "set null",
      }),
    patient_name: varchar("patient_name").notNull(),
    patient_email: varchar("patient_email").notNull(),
    patient_phone: varchar("patient_phone"),
    notes: varchar("notes"),
    status: enum_bookings_status("status").notNull().default("pending"),
    confirmation_token: varchar("confirmation_token").notNull(),
    created_at: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updated_at: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("bookings_service_id_idx").on(columns.service_id),
    uniqueIndex("bookings_time_slot_id_idx").on(columns.time_slot_id),
    uniqueIndex("bookings_confirmation_token_idx").on(
      columns.confirmation_token,
    ),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    adminsID: integer("admins_id"),
    mediaID: integer("media_id"),
    servicesID: varchar("services_id"),
    "time-slotsID": varchar("time_slots_id"),
    testimonialsID: varchar("testimonials_id"),
    bookingsID: varchar("bookings_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_admins_id_idx").on(columns.adminsID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_services_id_idx").on(
      columns.servicesID,
    ),
    index("payload_locked_documents_rels_time_slots_id_idx").on(
      columns["time-slotsID"],
    ),
    index("payload_locked_documents_rels_testimonials_id_idx").on(
      columns.testimonialsID,
    ),
    index("payload_locked_documents_rels_bookings_id_idx").on(
      columns.bookingsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["adminsID"]],
      foreignColumns: [admins.id],
      name: "payload_locked_documents_rels_admins_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["servicesID"]],
      foreignColumns: [services.id],
      name: "payload_locked_documents_rels_services_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["time-slotsID"]],
      foreignColumns: [time_slots.id],
      name: "payload_locked_documents_rels_time_slots_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["testimonialsID"]],
      foreignColumns: [testimonials.id],
      name: "payload_locked_documents_rels_testimonials_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["bookingsID"]],
      foreignColumns: [bookings.id],
      name: "payload_locked_documents_rels_bookings_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    adminsID: integer("admins_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_admins_id_idx").on(columns.adminsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["adminsID"]],
      foreignColumns: [admins.id],
      name: "payload_preferences_rels_admins_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const brand_settings = pgTable("brand_settings", {
  id: serial("id").primaryKey(),
  name: varchar("name").notNull().default("PrimaCura Physio"),
  tagline: varchar("tagline").notNull().default("Move Better. Live Better."),
  description: varchar("description")
    .notNull()
    .default("Expert physiotherapy in the heart of Vienna."),
  email: varchar("email").notNull().default("hello@primacura.at"),
  phone: varchar("phone").notNull().default("+43 1 234 5678"),
  address: varchar("address")
    .notNull()
    .default("Mariahilfer Strasse 12, 1060 Wien"),
  logo_url: varchar("logo_url").notNull().default("/images/logo.svg"),
  socials_instagram: varchar("socials_instagram").default(
    "https://instagram.com/primacura",
  ),
  socials_facebook: varchar("socials_facebook").default(
    "https://facebook.com/primacura",
  ),
  colors_primary: varchar("colors_primary").default("#2A6B5E"),
  colors_secondary: varchar("colors_secondary").default("#E8F4F1"),
  colors_accent: varchar("colors_accent").default("#F0A500"),
  fonts_heading: varchar("fonts_heading").default("Playfair Display"),
  fonts_body: varchar("fonts_body").default("DM Sans"),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_admins_sessions = relations(
  admins_sessions,
  ({ one }) => ({
    _parentID: one(admins, {
      fields: [admins_sessions._parentID],
      references: [admins.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_admins = relations(admins, ({ many }) => ({
  sessions: many(admins_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_services = relations(services, () => ({}));
export const relations_time_slots = relations(time_slots, () => ({}));
export const relations_testimonials = relations(testimonials, () => ({}));
export const relations_bookings = relations(bookings, ({ one }) => ({
  service_id: one(services, {
    fields: [bookings.service_id],
    references: [services.id],
    relationName: "service_id",
  }),
  time_slot_id: one(time_slots, {
    fields: [bookings.time_slot_id],
    references: [time_slots.id],
    relationName: "time_slot_id",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    adminsID: one(admins, {
      fields: [payload_locked_documents_rels.adminsID],
      references: [admins.id],
      relationName: "admins",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    servicesID: one(services, {
      fields: [payload_locked_documents_rels.servicesID],
      references: [services.id],
      relationName: "services",
    }),
    "time-slotsID": one(time_slots, {
      fields: [payload_locked_documents_rels["time-slotsID"]],
      references: [time_slots.id],
      relationName: "time-slots",
    }),
    testimonialsID: one(testimonials, {
      fields: [payload_locked_documents_rels.testimonialsID],
      references: [testimonials.id],
      relationName: "testimonials",
    }),
    bookingsID: one(bookings, {
      fields: [payload_locked_documents_rels.bookingsID],
      references: [bookings.id],
      relationName: "bookings",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    adminsID: one(admins, {
      fields: [payload_preferences_rels.adminsID],
      references: [admins.id],
      relationName: "admins",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_brand_settings = relations(brand_settings, () => ({}));

type DatabaseSchema = {
  enum_bookings_status: typeof enum_bookings_status;
  admins_sessions: typeof admins_sessions;
  admins: typeof admins;
  media: typeof media;
  services: typeof services;
  time_slots: typeof time_slots;
  testimonials: typeof testimonials;
  bookings: typeof bookings;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  brand_settings: typeof brand_settings;
  relations_admins_sessions: typeof relations_admins_sessions;
  relations_admins: typeof relations_admins;
  relations_media: typeof relations_media;
  relations_services: typeof relations_services;
  relations_time_slots: typeof relations_time_slots;
  relations_testimonials: typeof relations_testimonials;
  relations_bookings: typeof relations_bookings;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_brand_settings: typeof relations_brand_settings;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
